### ISSUE TITLE
Multi-line response behavior is incorrect.

### ISSUE THREAD

**Issue by Yawning** [DevelHell/popgun#1]
RFC 1939:
> If any line of the multi-line response begins with the termination octet, the line is "byte-stuffed" by pre-pending the termination octet to that line of the response.   Hence a multi-line response is terminated with the five octets "CRLF.CRLF".

The code:
~~~
// command.go:RetrCommand.Run() 
	lines := strings.Split(message, "\r\n")
	c.printer.Ok("")
        c.printer.MultiLine(lines)

// popgun.go:
func (p Printer) MultiLine(msgs []string) {
	for _, line := range msgs {
		fmt.Fprintf(p.conn, "%s\r\n", line)
	}
	fmt.Fprint(p.conn, ".\r\n")
}
~~~

Testcase:
~~~
What happens on a RETR or TOP (when supported) if a message happens to look like
.
this?
~~~

**Comment by peterkrejci** [comment]
Sorry for late response, this issue should be now fixed. Thanks for reporting!
